import type { Metadata } from "next";
import "@/styles/globals.scss";
import ReactQueryProvider from "@/components/providers/react-query-provider";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "WebDex - Know your Pokemons",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <Navbar />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
